sudo: false
language: 
  - go
go:
  - 1.8.3

#before_install:
  #- git rm -r --cached .
  #- git add .
  #- git commit -m 'update .gitignore'
install:
  - go get -v github.com/golang/lint/golint
  #- go get -d -t -v ./tree/develop/sm2
  #- go get -d -t -v ./tree/develop/sm3
  #- go get -d -t -v ./tree/develop/sm4
  - go build -v ./sm2
  - go build -v ./sm3
  - go build -v ./sm4

script:
  - go vet ./sm2
  - go vet ./sm3
  - go vet ./sm4
  - $HOME/gopath/bin/golint .
 # - go test -v ./sm2
  - go test -v ./sm3
  - go test -v ./sm4

after_failure:

 - |
  echo "Error!"

notifications:
  email: false
