sudo: false

language: 
  - go
go:
  - 1.8.3

install:
  - go get -v github.com/golang/lint/golint
 #- go get -v github.com/wangduotj/gmsm/gmssl    
  - go get -d -t -v ./...
  - go build -v ./...

script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...

notifications:
  email: false
